# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun Runtime
      uses: antongolub/action-setup-bun@v1
      with:
        bun-version: 0.2.0
        cache: true
        cache-bin: true

    - run: bun install
    - run: bun run build --if-present
    - run: bun run lint
    - run: bun test --coverage
    - run: bun run lint

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
